# E01 
# Nome: Wagner R.R.

# Ex. **1**

Importando uma função do módulo math, utilizando-a e guardando o valor em uma variável.

In [1]:
from math import cos as cos1

In [2]:
def cosseno(valor):
  return cos1(valor)

In [5]:
a = cosseno(1.5)

# Ex. **2**

Importando uma função do módulo numpy, utilizando-a e guardando o valor em uma variável.

In [ ]:
from math import cos as cos1
from numpy import cos as cos2

In [ ]:
def cosseno(valor):
  return cos2(valor)

In [ ]:
b = cosseno(1.5)

# Ex. **3**

Realizando a subtração entre as variáveis contendo o valor empregado na função "cos", logo após o resultado é guardado em uma nova variável.

In [ ]:
c = b-a
print(c)

0.0


# Ex. **4**

Ao realizar uma multiplicação entre uma lista e um número inteiro, a lista é duplicada.

In [ ]:
l = (1,2,3,4,5)
l = 2*l
print(l)

(1, 2, 3, 4, 5, 1, 2, 3, 4, 5)


# Ex. **5**

Tive problema em resolver está questão, pois estava tentando criar a matriz e depois obter a nova matriz após a multiplicação de "i" por "j", mas com ajuda do meu grupo pude chegar a resposta.


In [11]:
import numpy as np
m1 = np.arange(1,501).reshape(100,5)
m2 = np.arange(1,26).reshape(5,5)
m3 = np.dot(m1,m2)

In [12]:
mr = np.arange(1,501).reshape(100,5)
for i in range(100):
  for j in range(5):
    mr[i][j] = i*j
print(mr)

[[  0   0   0   0   0]
 [  0   1   2   3   4]
 [  0   2   4   6   8]
 [  0   3   6   9  12]
 [  0   4   8  12  16]
 [  0   5  10  15  20]
 [  0   6  12  18  24]
 [  0   7  14  21  28]
 [  0   8  16  24  32]
 [  0   9  18  27  36]
 [  0  10  20  30  40]
 [  0  11  22  33  44]
 [  0  12  24  36  48]
 [  0  13  26  39  52]
 [  0  14  28  42  56]
 [  0  15  30  45  60]
 [  0  16  32  48  64]
 [  0  17  34  51  68]
 [  0  18  36  54  72]
 [  0  19  38  57  76]
 [  0  20  40  60  80]
 [  0  21  42  63  84]
 [  0  22  44  66  88]
 [  0  23  46  69  92]
 [  0  24  48  72  96]
 [  0  25  50  75 100]
 [  0  26  52  78 104]
 [  0  27  54  81 108]
 [  0  28  56  84 112]
 [  0  29  58  87 116]
 [  0  30  60  90 120]
 [  0  31  62  93 124]
 [  0  32  64  96 128]
 [  0  33  66  99 132]
 [  0  34  68 102 136]
 [  0  35  70 105 140]
 [  0  36  72 108 144]
 [  0  37  74 111 148]
 [  0  38  76 114 152]
 [  0  39  78 117 156]
 [  0  40  80 120 160]
 [  0  41  82 123 164]
 [  0  42  84 126 168]
 [  0  43  

# Ex. **6**

Realizando a aplicação da função no intervalor de "-5" a "5", em seguida é utilizado a função "plot" do módulo importado matplotlib.

In [ ]:
import numpy as np
from matplotlib import pyplot as plt
x = np.linspace(-5,5,100)
y = 1.0/(1.0+np.exp(-x))
plt.plot(x,y)

# Ex. **7**

Implementação do código das classes "Quadrado" e "Triangulo", como descrito no vídeo.


In [ ]:
import numpy as np
class Quadrado:
  lado = 0
  def __init__(self,l):
    self.lado = l
  def area(self):
    return self.lado**2
class Triangulo:
  base = 0
  altura = 0
  def __init__(self,b,h):
    self.base = b
    self.altura = h
  def area(self):
    return self.base * self.altura / 2.0

In [ ]:
q1 = Quadrado(3)
q2 = Quadrado(4)
t1 = Triangulo(4,5)

print(q1.area())
print(q2.area())
print(t1.area())

# Ex. **8**

Implementação do código de classe para "Circulo", com a propriedade "raio" e a função "area".

In [ ]:
import numpy as np
class Quadrado:
  lado = 0
  def __init__(self,l):
    self.lado = l
  def area(self):
    return self.lado**2
class Triangulo:
  base = 0
  altura = 0
  def __init__(self,b,h):
    self.base = b
    self.altura = h
  def area(self):
    return self.base * self.altura / 2.0
class Circulo:
  raio = 0
  def __init__(self,r):
    self.raio = r
  def area(self):
    return np.pi*self.raio**2

In [ ]:
q1 = Quadrado(3)
t1 = Triangulo(4,5)
c1 = Circulo(2)

print(q1.area())
print(t1.area())
print(c1.area())

# Ex. **9**

Utilizando o código anterior, foi criado uma lista com 60 objetos sendo os 20 primeiros referentes a classe "Quadrado", entre 20 e 39 os da classe "Triangulo" e do 40 ao 59 os objetos da classe "Circulo". Todos os objetos foram criados com suas repectivas prorpriedades, onde cada um recebeu um valor aleatório de 1 a 10.

In [20]:
import numpy as np
class Quadrado:
  lado = 0
  def __init__(self,l):
    self.lado = l
  def area(self):
    return self.lado**2
class Triangulo:
  base = 0
  altura = 0
  def __init__(self,b,h):
    self.base = b
    self.altura = h
  def area(self):
    return self.base * self.altura / 2.0
class Circulo:
  raio = 0
  def __init__(self,r):
    self.raio = r
  def area(self):
    return np.pi*self.raio**2

In [ ]:
lista = np.zeros(60)
for i in range(59):
  if i < 20:
    q = Quadrado(np.random.randint(1,10))
    lista[i] = q.area()
  elif i < 40:
    t = Triangulo(np.random.randint(1,10),np.random.randint(1,10))
    lista[i] = t.area()
  else: 
    c = Circulo(np.random.randint(1,10))
    lista[i] = c.area()
#lista = lista.reshape(3,20)
print(lista)

# Ex. **10**

Foi realizado a importação do módulo random para que pude-se utilizar a função "shuffle()", realizando o embaralhamento da ordem dos elementos da lista.

In [129]:
import numpy as np
class Quadrado:
  lado = 0
  def __init__(self,l):
    self.lado = l
  def area(self):
    return self.lado**2
class Triangulo:
  base = 0
  altura = 0
  def __init__(self,b,h):
    self.base = b
    self.altura = h
  def area(self):
    return self.base * self.altura / 2.0
class Circulo:
  raio = 0
  def __init__(self,r):
    self.raio = r
  def area(self):
    return np.pi*self.raio**2

In [ ]:
lista= []
for i in range(59):
  if i < 20:
    lista.append(Quadrado(np.random.randint(1,10)))
  elif i < 40:
    lista.append(Triangulo(np.random.randint(1,10),np.random.randint(1,10)))
  else:
    lista.append(Circulo(np.random.randint(1,10)))

print(lista)

In [ ]:
import random
random.shuffle(lista)
resultados=[]
for i in lista:
  resultados.append(i.area())

print(lista)
print(resultados)


# Ex. **11**

Utilizando a função "sum()" foi somado todos os elementos da lista e mostrado na tela.

In [ ]:
print("Soma de todas as areas e '{}'".format(sum(resultados)))